[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
morph = "https://rpc-quicknode-holesky.morphl2.io"
[etherscan]
morph = { key = "${ETHERSCAN_API_KEY}", url = "https://explorer-holesky.morphl2.io/api" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
